spring.application.name=eatcommerce-backend
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ycsrrmemkhncwiexaywk
spring.datasource.password=Udeaeatcommerce2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

jwt.secret=ZWF0Y29tbWVyY2VKd3RTZWNyZXRTdXBlclNlZ3VybzIwMjU=

cloudinary.cloud_name=dznid9nrm
cloudinary.api_key=622872512634473
cloudinary.api_secret=bLXq07izzufrommeTYUw_ey_mZ4